import { SpaceType, Space } from "./types";

export const SPACE_TYPES: { name: SpaceType; icon: string }[] = [
  { name: "Backyards", icon: "🌳" },
  { name: "Pools", icon: "🏊" },
  { name: "Outdoor kitchens", icon: "🍽️" },
  { name: "Patios & decks", icon: "🪑" },
  { name: "Gardens", icon: "🌸" },
  { name: "Fire pits", icon: "🔥" },
  { name: "Rooftops", icon: "🏙️" },
  { name: "Sport courts", icon: "🏀" },
  { name: "Event yards", icon: "🎉" },
  { name: "Hot tubs", icon: "♨️" },
];

const u = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1200&q=70`;

// Curated outdoor image bank (backyard / pool / patio / garden shots)
const IMG = {
  poolModern: u("1600585154340-be6161a56a0c"),
  poolInfinity: u("1613490493576-7fde63acd811"),
  poolResort: u("1571003123894-1f0594d2b5d9"),
  poolLoungers: u("1572331165267-854da2b10ccc"),
  poolAerial: u("1523362628745-0c100150b504"),
  poolBackyard: u("1576013551627-0cc20b96c2a7"),
  patioTable: u("1416331108676-a22ccb276e35"),
  patioLights: u("1464366400600-7168b8af9bc3"),
  deck: u("1523986371872-9d3ba2e2f642"),
  garden: u("1558904541-efa843a96f01"),
  gardenPath: u("1585320806297-9794b3e4eeae"),
  greenhouse: u("1416879595882-3373a0480b5b"),
  firePit: u("1533105079780-92b9be482077"),
  grill: u("1544025162-d76694265947"),
  outdoorKitchen: u("1600891964092-4316c288032e"),
  rooftop: u("1533050487297-09b450131914"),
  lawn: u("1558618666-fcd25c85cd64"),
  hotTub: u("1580977276076-ae4b8c219b8e"),
};

export const SPACES: Space[] = [
  {
    id: "sunlit-oasis-la",
    title: "Sunlit backyard oasis with pool & cabana",
    location: "Los Angeles, CA",
    neighborhood: "Sherman Oaks",
    spaceType: "Backyards",
    hourlyPrice: 65,
    dayPrice: 420,
    minHours: 2,
    rating: 4.97,
    reviews: 214,
    capacity: 25,
    acres: 0.3,
    topHost: true,
    lat: 34.1508,
    lng: -118.4489,
    images: [IMG.poolModern, IMG.poolLoungers, IMG.patioLights, IMG.grill],
    host: { name: "Sofia", since: "2022", avatar: "https://i.pravatar.cc/150?img=1", responseRate: 100 },
    description:
      "A private, resort-style backyard perfect for birthday parties, photo shoots, and weekend hangs. Heated pool, shaded cabana, lounge seating, and a built-in BBQ — all tucked behind tall privacy hedges.",
    amenities: ["Heated pool", "BBQ grill", "Cabana", "Lounge seating", "Outdoor speakers", "Restroom access", "Free parking", "String lights"],
    rules: ["No smoking", "Quiet hours after 9pm", "Guests must stay in backyard area", "No glass in the pool"],
  },
  {
    id: "desert-pool-phx",
    title: "Desert pool retreat with misters",
    location: "Phoenix, AZ",
    neighborhood: "Arcadia",
    spaceType: "Pools",
    hourlyPrice: 45,
    dayPrice: 300,
    minHours: 2,
    rating: 4.93,
    reviews: 168,
    capacity: 20,
    acres: 0.25,
    topHost: true,
    lat: 33.4942,
    lng: -111.9819,
    images: [IMG.poolResort, IMG.poolAerial, IMG.patioTable, IMG.hotTub],
    host: { name: "Diego", since: "2021", avatar: "https://i.pravatar.cc/150?img=12", responseRate: 98 },
    description:
      "Beat the heat in this sparkling Arcadia pool with cooling misters, in-water bar stools, and mountain views. A favorite for pool parties and family gatherings all summer long.",
    amenities: ["Pool", "Misting system", "Swim-up bar", "Hot tub", "Loungers", "Shade sails", "Bluetooth speaker", "Restroom access"],
    rules: ["No lifeguard on duty", "Children must be supervised", "No pets in pool", "Clean up before leaving"],
  },
  {
    id: "chef-patio-austin",
    title: "Chef's outdoor kitchen & dining deck",
    location: "Austin, TX",
    neighborhood: "Zilker",
    spaceType: "Outdoor kitchens",
    hourlyPrice: 55,
    dayPrice: 360,
    minHours: 3,
    rating: 4.99,
    reviews: 132,
    capacity: 16,
    acres: 0.15,
    topHost: true,
    lat: 30.2669,
    lng: -97.7729,
    images: [IMG.outdoorKitchen, IMG.grill, IMG.deck, IMG.patioLights],
    host: { name: "Marcus", since: "2020", avatar: "https://i.pravatar.cc/150?img=15", responseRate: 100 },
    description:
      "A fully-equipped outdoor kitchen built for hosts who love to cook. Pro gas grill, pizza oven, prep island, and a covered dining deck that seats sixteen. Ideal for supper clubs and cooking classes.",
    amenities: ["Gas grill", "Pizza oven", "Prep island", "Covered dining", "Refrigerator", "Sink", "String lights", "Restroom access"],
    rules: ["Leave kitchen clean", "No deep frying", "Propane included", "No smoking near food"],
  },
  {
    id: "garden-hideaway-atl",
    title: "Lush garden hideaway for events",
    location: "Atlanta, GA",
    neighborhood: "Virginia-Highland",
    spaceType: "Gardens",
    hourlyPrice: 40,
    dayPrice: 280,
    minHours: 2,
    rating: 4.95,
    reviews: 201,
    capacity: 30,
    acres: 0.4,
    topHost: false,
    lat: 33.7825,
    lng: -84.3538,
    images: [IMG.garden, IMG.gardenPath, IMG.greenhouse, IMG.patioTable],
    host: { name: "Ava", since: "2023", avatar: "https://i.pravatar.cc/150?img=25", responseRate: 96 },
    description:
      "A romantic, ivy-draped garden with winding stone paths, a wisteria arbor, and a vintage greenhouse. Beloved for micro-weddings, bridal showers, and dreamy photo sessions.",
    amenities: ["Landscaped garden", "Greenhouse", "Arbor", "Bistro seating", "Power outlets", "Restroom access", "Free parking", "String lights"],
    rules: ["No confetti or rice", "Stay on paths", "No open flames", "Vendors welcome"],
  },
  {
    id: "firepit-lawn-nash",
    title: "Fire-pit lawn under the stars",
    location: "Nashville, TN",
    neighborhood: "East Nashville",
    spaceType: "Fire pits",
    hourlyPrice: 35,
    dayPrice: 220,
    minHours: 2,
    rating: 4.9,
    reviews: 88,
    capacity: 18,
    acres: 0.35,
    topHost: false,
    lat: 36.1785,
    lng: -86.7405,
    images: [IMG.firePit, IMG.lawn, IMG.patioLights, IMG.deck],
    host: { name: "Cole", since: "2022", avatar: "https://i.pravatar.cc/150?img=33", responseRate: 94 },
    description:
      "A wide open lawn with a stone fire pit, Adirondack chairs, and café lights strung overhead. The go-to spot for s'mores nights, acoustic sets, and laid-back get-togethers.",
    amenities: ["Fire pit", "Firewood", "Adirondack chairs", "String lights", "Lawn games", "Bluetooth speaker", "Restroom access", "Free parking"],
    rules: ["Fires out by 10pm", "No fireworks", "Supervise the fire", "Respect neighbors"],
  },
  {
    id: "resort-backyard-miami",
    title: "Tropical resort backyard with tiki bar",
    location: "Miami, FL",
    neighborhood: "Coconut Grove",
    spaceType: "Backyards",
    hourlyPrice: 85,
    dayPrice: 560,
    minHours: 3,
    rating: 4.96,
    reviews: 176,
    capacity: 40,
    acres: 0.45,
    topHost: true,
    lat: 25.7126,
    lng: -80.2568,
    images: [IMG.poolBackyard, IMG.poolResort, IMG.patioLights, IMG.hotTub],
    host: { name: "Lucia", since: "2019", avatar: "https://i.pravatar.cc/150?img=9", responseRate: 100 },
    description:
      "A slice of the tropics in the Grove: lagoon-style pool, palm-shaded tiki bar, hammocks, and a sound system. Built for milestone birthdays, brand shoots, and unforgettable parties.",
    amenities: ["Lagoon pool", "Tiki bar", "Hot tub", "Sound system", "Hammocks", "Palapa shade", "Restroom access", "Valet parking"],
    rules: ["No smoking", "Security required over 25 guests", "Quiet hours after 10pm", "Wristbands provided"],
  },
  {
    id: "modern-deck-denver",
    title: "Modern patio & deck with mountain views",
    location: "Denver, CO",
    neighborhood: "Highlands",
    spaceType: "Patios & decks",
    hourlyPrice: 42,
    dayPrice: 290,
    minHours: 2,
    rating: 4.88,
    reviews: 74,
    capacity: 14,
    acres: 0.12,
    topHost: false,
    lat: 39.7621,
    lng: -105.0141,
    images: [IMG.deck, IMG.patioTable, IMG.firePit, IMG.patioLights],
    host: { name: "Nora", since: "2023", avatar: "https://i.pravatar.cc/150?img=45", responseRate: 92 },
    description:
      "A sleek multi-level deck with a built-in fire table, sectional lounge, and sweeping views of the Front Range. A calm, design-forward backdrop for dinners and small celebrations.",
    amenities: ["Fire table", "Sectional lounge", "Dining table", "Heaters", "String lights", "Mountain view", "Restroom access", "Free parking"],
    rules: ["No smoking", "14 guests max", "No amplified music after 9pm", "Shoes off inside"],
  },
  {
    id: "rooftop-yard-chicago",
    title: "Rooftop garden yard in the city",
    location: "Chicago, IL",
    neighborhood: "West Loop",
    spaceType: "Rooftops",
    hourlyPrice: 70,
    dayPrice: 480,
    minHours: 3,
    rating: 4.92,
    reviews: 109,
    capacity: 35,
    acres: 0.1,
    topHost: true,
    lat: 41.8837,
    lng: -87.6522,
    images: [IMG.rooftop, IMG.patioLights, IMG.garden, IMG.deck],
    host: { name: "Priya", since: "2021", avatar: "https://i.pravatar.cc/150?img=20", responseRate: 99 },
    description:
      "An elevated rooftop yard with turf lawn, planters, lounge pods, and a skyline view that steals the show at golden hour. Popular for launch parties and rooftop cinema nights.",
    amenities: ["Skyline view", "Turf lawn", "Lounge pods", "Bar counter", "String lights", "Elevator access", "Restroom access", "Projector"],
    rules: ["No smoking", "Keep off the ledge", "Building quiet hours 11pm", "No open flames"],
  },
  {
    id: "sport-yard-dallas",
    title: "Backyard sport court & turf",
    location: "Dallas, TX",
    neighborhood: "Lakewood",
    spaceType: "Sport courts",
    hourlyPrice: 38,
    dayPrice: 240,
    minHours: 2,
    rating: 4.85,
    reviews: 63,
    capacity: 22,
    acres: 0.28,
    topHost: false,
    lat: 32.8121,
    lng: -96.7345,
    images: [IMG.lawn, IMG.deck, IMG.grill, IMG.patioTable],
    host: { name: "Trey", since: "2022", avatar: "https://i.pravatar.cc/150?img=51", responseRate: 95 },
    description:
      "A half-court with hoop, putting green, and turf play area — plus a shaded patio and grill. Great for kids' parties, team practices, and family field days.",
    amenities: ["Basketball hoop", "Putting green", "Turf field", "BBQ grill", "Shaded patio", "Water station", "Restroom access", "Free parking"],
    rules: ["Athletic shoes only", "No cleats on turf", "Supervise children", "Return equipment"],
  },
  {
    id: "event-yard-sd",
    title: "Grand event yard with ocean breeze",
    location: "San Diego, CA",
    neighborhood: "Encinitas",
    spaceType: "Event yards",
    hourlyPrice: 95,
    dayPrice: 650,
    minHours: 4,
    rating: 4.98,
    reviews: 145,
    capacity: 60,
    acres: 0.6,
    topHost: true,
    lat: 33.0370,
    lng: -117.2920,
    images: [IMG.patioLights, IMG.garden, IMG.poolLoungers, IMG.deck],
    host: { name: "Isla", since: "2018", avatar: "https://i.pravatar.cc/150?img=5", responseRate: 100 },
    description:
      "An expansive coastal yard with a lawn for a tent, a paved patio for dancing, ocean breezes, and sunset light. Purpose-built for weddings, showers, and large celebrations.",
    amenities: ["Ceremony lawn", "Dance patio", "Catering prep area", "Power hookups", "Restrooms x2", "Bridal suite", "Parking for 20", "String lights"],
    rules: ["Insurance required", "Amplified music off by 10pm", "Licensed vendors only", "No rice/confetti"],
  },
  {
    id: "cozy-hottub-seattle",
    title: "Cedar hot tub & fern garden",
    location: "Seattle, WA",
    neighborhood: "Ballard",
    spaceType: "Hot tubs",
    hourlyPrice: 30,
    dayPrice: 190,
    minHours: 2,
    rating: 4.91,
    reviews: 97,
    capacity: 8,
    acres: 0.1,
    topHost: false,
    lat: 47.6685,
    lng: -122.3830,
    images: [IMG.hotTub, IMG.garden, IMG.gardenPath, IMG.firePit],
    host: { name: "Owen", since: "2023", avatar: "https://i.pravatar.cc/150?img=68", responseRate: 93 },
    description:
      "A tucked-away cedar hot tub surrounded by ferns and fairy lights — the coziest spot in the Northwest for a small soak session with friends on a misty evening.",
    amenities: ["Cedar hot tub", "Fern garden", "Fairy lights", "Towels", "Changing area", "Bluetooth speaker", "Restroom access", "Covered seating"],
    rules: ["Shower before use", "8 guests max", "No glass", "Quiet after 9pm"],
  },
  {
    id: "poolside-kitchen-houston",
    title: "Poolside patio with outdoor kitchen",
    location: "Houston, TX",
    neighborhood: "The Heights",
    spaceType: "Backyards",
    hourlyPrice: 58,
    dayPrice: 380,
    minHours: 2,
    rating: 4.94,
    reviews: 156,
    capacity: 28,
    acres: 0.32,
    topHost: true,
    lat: 29.8005,
    lng: -95.3980,
    images: [IMG.poolInfinity, IMG.outdoorKitchen, IMG.patioTable, IMG.grill],
    host: { name: "Bianca", since: "2021", avatar: "https://i.pravatar.cc/150?img=60", responseRate: 100 },
    description:
      "The complete backyard package: sparkling pool, full outdoor kitchen, covered patio, and dining for a crowd. A one-stop spot for graduations, reunions, and summer cookouts.",
    amenities: ["Pool", "Outdoor kitchen", "Covered patio", "Dining tables", "Grill", "Sound system", "Restroom access", "Free parking"],
    rules: ["No smoking", "Kids supervised in pool", "Clean grill after use", "Quiet hours after 10pm"],
  },
];

export function getSpace(id: string): Space | undefined {
  return SPACES.find((s) => s.id === id);
}
